name: parking_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  async_loader: ^0.1.2
  bloc: ^8.0.2
  camera: ^0.9.4+14
  cloud_firestore: ^3.1.9
  contacts_service: ^0.6.3
  custom_switch_button: ^0.5.0
#  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  ext_video_player: ^0.1.0
  fancy_bottom_navigation: ^0.3.2
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.7
  firebase_storage: ^10.2.8
  flushbar: ^1.10.4
  flutter_dotenv: ^5.0.2
#  flutter_facebook_auth: ^1.0.2+2
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^9.2.0
  geocoding: ^2.0.2
  geoflutterfire: ^3.0.3
  geolocator: ^8.2.0
  get_it: ^7.2.0
  google_fonts: ^2.3.0
  google_maps_flutter: ^2.1.1
  google_sign_in: ^5.2.4
  http:
  image_picker: ^0.8.4+10
#  international_phone_input: ^1.0.4
  logger: ^1.1.0
  permission_handler: ^9.2.0
  provider: ^6.0.2
  sealed_unions: ^3.0.2+2
  share: ^2.0.4
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  video_player: ^2.2.19
  solid_bottom_sheet: ^0.1.9
  location: ^4.3.0
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
#  sentry: ">=3.0.0 <4.0.0"
  firebase_analytics:
  flutter_rating: ^0.0.2
#  stripe_payment: ^1.1.3
  # flutter_stripe_payment: ^0.0.12
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  on_boarding_ui: ^0.0.4
  date_format:
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700


  assets:
    - assets/images/
    - assets/icons/
#  - assets/images/slide_2.png
#  - assets/images/slide_3.png
#  - assets/background.png
#   - images/a_dot_ham.jpeg
